// sounds.mjs -- GENERATED by test/tools/gen_info.py from
// reference_materials/doom/linuxdoom-1.10/ (sounds.h, sounds.c) -- DO NOT EDIT BY HAND.
//
// Part of tsvm-doom, a derivative of linuxdoom-1.10 (C) id Software.
// Licensed under GPL-2.0-only; see COPYING.

// injectIntChk sink -- keep first of each loop kind throwaway
while (false) {} for (;false;) {} do {} while (false);

const NUMSFX = 109
const NUMMUSIC = 68

const sfx = {
sfx_None:0,sfx_pistol:1,sfx_shotgn:2,sfx_sgcock:3,sfx_dshtgn:4,sfx_dbopn:5,
sfx_dbcls:6,sfx_dbload:7,sfx_plasma:8,sfx_bfg:9,sfx_sawup:10,sfx_sawidl:11,
sfx_sawful:12,sfx_sawhit:13,sfx_rlaunc:14,sfx_rxplod:15,sfx_firsht:16,sfx_firxpl:17,
sfx_pstart:18,sfx_pstop:19,sfx_doropn:20,sfx_dorcls:21,sfx_stnmov:22,sfx_swtchn:23,
sfx_swtchx:24,sfx_plpain:25,sfx_dmpain:26,sfx_popain:27,sfx_vipain:28,sfx_mnpain:29,
sfx_pepain:30,sfx_slop:31,sfx_itemup:32,sfx_wpnup:33,sfx_oof:34,sfx_telept:35,
sfx_posit1:36,sfx_posit2:37,sfx_posit3:38,sfx_bgsit1:39,sfx_bgsit2:40,sfx_sgtsit:41,
sfx_cacsit:42,sfx_brssit:43,sfx_cybsit:44,sfx_spisit:45,sfx_bspsit:46,sfx_kntsit:47,
sfx_vilsit:48,sfx_mansit:49,sfx_pesit:50,sfx_sklatk:51,sfx_sgtatk:52,sfx_skepch:53,
sfx_vilatk:54,sfx_claw:55,sfx_skeswg:56,sfx_pldeth:57,sfx_pdiehi:58,sfx_podth1:59,
sfx_podth2:60,sfx_podth3:61,sfx_bgdth1:62,sfx_bgdth2:63,sfx_sgtdth:64,sfx_cacdth:65,
sfx_skldth:66,sfx_brsdth:67,sfx_cybdth:68,sfx_spidth:69,sfx_bspdth:70,sfx_vildth:71,
sfx_kntdth:72,sfx_pedth:73,sfx_skedth:74,sfx_posact:75,sfx_bgact:76,sfx_dmact:77,
sfx_bspact:78,sfx_bspwlk:79,sfx_vilact:80,sfx_noway:81,sfx_barexp:82,sfx_punch:83,
sfx_hoof:84,sfx_metal:85,sfx_chgun:86,sfx_tink:87,sfx_bdopn:88,sfx_bdcls:89,
sfx_itmbk:90,sfx_flame:91,sfx_flamst:92,sfx_getpow:93,sfx_bospit:94,sfx_boscub:95,
sfx_bossit:96,sfx_bospn:97,sfx_bosdth:98,sfx_manatk:99,sfx_mandth:100,sfx_sssit:101,
sfx_ssdth:102,sfx_keenpn:103,sfx_keendt:104,sfx_skeact:105,sfx_skesit:106,sfx_skeatk:107,
sfx_radio:108,
}
const mus = {
mus_None:0,mus_e1m1:1,mus_e1m2:2,mus_e1m3:3,mus_e1m4:4,mus_e1m5:5,
mus_e1m6:6,mus_e1m7:7,mus_e1m8:8,mus_e1m9:9,mus_e2m1:10,mus_e2m2:11,
mus_e2m3:12,mus_e2m4:13,mus_e2m5:14,mus_e2m6:15,mus_e2m7:16,mus_e2m8:17,
mus_e2m9:18,mus_e3m1:19,mus_e3m2:20,mus_e3m3:21,mus_e3m4:22,mus_e3m5:23,
mus_e3m6:24,mus_e3m7:25,mus_e3m8:26,mus_e3m9:27,mus_inter:28,mus_intro:29,
mus_bunny:30,mus_victor:31,mus_introa:32,mus_runnin:33,mus_stalks:34,mus_countd:35,
mus_betwee:36,mus_doom:37,mus_the_da:38,mus_shawn:39,mus_ddtblu:40,mus_in_cit:41,
mus_dead:42,mus_stlks2:43,mus_theda2:44,mus_doom2:45,mus_ddtbl2:46,mus_runni2:47,
mus_dead2:48,mus_stlks3:49,mus_romero:50,mus_shawn2:51,mus_messag:52,mus_count2:53,
mus_ddtbl3:54,mus_ampie:55,mus_theda3:56,mus_adrian:57,mus_messg2:58,mus_romer2:59,
mus_tense:60,mus_shawn3:61,mus_openin:62,mus_evil:63,mus_ultima:64,mus_read_m:65,
mus_dm2ttl:66,mus_dm2int:67,
}
const sfxNames = [
"none","pistol","shotgn","sgcock","dshtgn","dbopn","dbcls","dbload","plasma","bfg",
"sawup","sawidl","sawful","sawhit","rlaunc","rxplod","firsht","firxpl","pstart","pstop",
"doropn","dorcls","stnmov","swtchn","swtchx","plpain","dmpain","popain","vipain","mnpain",
"pepain","slop","itemup","wpnup","oof","telept","posit1","posit2","posit3","bgsit1",
"bgsit2","sgtsit","cacsit","brssit","cybsit","spisit","bspsit","kntsit","vilsit","mansit",
"pesit","sklatk","sgtatk","skepch","vilatk","claw","skeswg","pldeth","pdiehi","podth1",
"podth2","podth3","bgdth1","bgdth2","sgtdth","cacdth","skldth","brsdth","cybdth","spidth",
"bspdth","vildth","kntdth","pedth","skedth","posact","bgact","dmact","bspact","bspwlk",
"vilact","noway","barexp","punch","hoof","metal","chgun","tink","bdopn","bdcls",
"itmbk","flame","flamst","getpow","bospit","boscub","bossit","bospn","bosdth","manatk",
"mandth","sssit","ssdth","keenpn","keendt","skeact","skesit","skeatk","radio",
]
const sfxSingularity = new Int32Array([
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,1,1,1,1,
1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,
1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,
])
const sfxPriority = new Int32Array([
0,64,64,64,64,64,64,64,64,64,64,118,64,64,64,70,70,70,100,100,
100,100,119,78,78,96,96,96,96,96,96,78,78,78,96,32,98,98,98,98,
98,98,98,94,92,90,90,90,90,90,90,70,70,70,70,70,70,32,32,70,
70,70,70,70,70,70,70,32,32,32,32,32,32,32,32,120,120,120,100,100,
100,78,60,64,70,70,64,60,100,100,100,32,32,60,70,70,70,70,70,70,
70,70,70,70,70,70,70,70,60,
])
const sfxLink = new Int32Array([
-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
-1,-1,-1,-1,-1,-1,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
-1,-1,-1,-1,-1,-1,-1,-1,-1,
])
const sfxPitch = new Int32Array([
-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
-1,-1,-1,-1,-1,-1,150,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
-1,-1,-1,-1,-1,-1,-1,-1,-1,
])
const sfxVolume = new Int32Array([
-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
-1,-1,-1,-1,-1,-1,0,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
-1,-1,-1,-1,-1,-1,-1,-1,-1,
])
const musNames = [
null,"e1m1","e1m2","e1m3","e1m4","e1m5","e1m6","e1m7","e1m8","e1m9",
"e2m1","e2m2","e2m3","e2m4","e2m5","e2m6","e2m7","e2m8","e2m9","e3m1",
"e3m2","e3m3","e3m4","e3m5","e3m6","e3m7","e3m8","e3m9","inter","intro",
"bunny","victor","introa","runnin","stalks","countd","betwee","doom","the_da","shawn",
"ddtblu","in_cit","dead","stlks2","theda2","doom2","ddtbl2","runni2","dead2","stlks3",
"romero","shawn2","messag","count2","ddtbl3","ampie","theda3","adrian","messg2","romer2",
"tense","shawn3","openin","evil","ultima","read_m","dm2ttl","dm2int",
]

exports = {
    NUMSFX, NUMMUSIC, sfx, mus, sfxNames,
    sfxSingularity, sfxPriority, sfxLink, sfxPitch, sfxVolume,
    musNames,
    init: function (D) {},
}
